# SPDX-FileCopyrightText: Copyright (c) 2026 lkmavi
# SPDX-License-Identifier: MIT
#
# Default osg sandbox policy.

version: 1
filesystem_policy:
  include_workdir: true
  read_only:
  - /usr
  - /lib
  - /proc
  - /dev/urandom
  - /app
  - /etc
  - /var/log
  read_write:
  - /tmp
  - /dev/null
  - /osg/data
landlock:
  compatibility: best_effort
network_policies: {}
inference:
  providers:
  - anthropic
  - openai
display:
  mode: none
  publish: 127.0.0.1
  port: 6080
  auth: password
  browser: chromium
credentials:
  env_allow:
  - TERM
  - LANG
  - COLORTERM
  - ANTHROPIC_API_KEY
  - OPENAI_API_KEY
  - DISPLAY
  write_to_disk: false
